services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - ares-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ares-net

networks:
  ares-net:
